language: java
script:
- cd ./src/communication
- mvn install -Dmaven.javadoc.skip=true -B
- cd ..
- cd ..
- cd ./src/moped/ -Dmaven.javadoc.skip=true -B
- mvn test -Dmaven.javadoc.skip=true -B

notifications:
    slack: moppepojkar:nC9dOhmtdPoSgbW3Awqm9p92
