@startuml
Communicator <-- AbstractCommunicator
AbstractCommunicator <-- ClientCommunicator
AbstractCommunicator <-- ServerCommunicator
Communicator o- CommunicationListener
MopedState -o AbstractCommunicator
MopedState -o Communicator


interface Communicator

interface CommunicationListener

abstract class AbstractCommunicator

class ClientCommunicator

class ServerCommunicator

Enum MopedState {
  MANUAL = 0
  ACC= 1
}
@enduml